##############################################################################
##### DoomMake Properties File
#####
##### Contains common properties that you would want to set 
##### for your project. This file should be ignored by your repository.
#####
##### The values in this file end up as values in the "properties" scope.
#####
##### REMINDER: Properties files have a special handling for strings!
##### Backslashes may not do what you think they do, here!
##### See: https://en.wikipedia.org/wiki/.properties
##############################################################################

## IWAD Path
## Sets the path to the IWAD used by this project.
doommake.iwad=freedoom2.wad

## Build Directory
## Sets the project build directory.
## Leave blank for default.
doommake.dir.build=

## Distribution Directory
## Sets the project distribution directory.
## Leave blank for default.
doommake.dir.dist=

## Source Directory
## Sets the project source directory.
## Leave blank for default.
doommake.dir.src=

## Lock File Name
## Sets the lock file name. Created in build directory.
## Leave blank for default.
doommake.file.lock=

## DeHackEd Patch Output File
## Sets the name of the DeHackEd patch compiled from DECOHack. Created in build directory.
## Leave blank for default.
doommake.file.patch=

## DeHackEd Patch Source Output File
## Sets the name of the combined DeHackEd patch source compiled from DECOHack. Created in build directory.
## Leave blank for default.
doommake.file.patch.src=

## Asset WAD
## Sets the name of the asset WAD. Created in build directory.
## Leave blank for default.
doommake.file.assets=

## Map WAD
## Sets the name of the output maps WAD. Created in build directory.
## Leave blank for default.
doommake.file.maps=

## Map Textures WAD
## Sets the name of the output WAD for extracted textures. Created in build directory.
## Leave blank for default.
doommake.file.maptex=

## Path to testing executable.
## Sets the name of the EXE to call to run this project.
doommake.run.exe=

## Path to testing executable working directory.
## Sets the working directory of the program.
## Leave blank for the parent directory of the executable.
doommake.run.exe.workdir=

## The port's IWAD switch.
## Sets the argument switch to use for specifying the IWAD to the port.
## Leave blank for `-iwad`
doommake.run.switch.iwad=

## The port's File switch.
## Sets the argument switch to use for specifying the files to load.
## Leave blank for `-file`
doommake.run.switch.file=

## The port's DeHackEd switch.
## Sets the argument switch to use for specifying the DeHackEd patch.
## Leave blank for `-deh`
doommake.run.switch.deh=

